spring:

  datasource:
    url: jdbc:h2:file:./data/techsolutions
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pazzamoranomoisesalejandro@gmail.com
    password: "zjul nrdo jbwy zifj"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8080